### ISSUE TITLE
pip install failing on redhat 7

### ISSUE THREAD

**Issue by mg03** [cablehead/vanilla.consul#3]
pip install vanilla.consul
Collecting vanilla.consul
Requirement already satisfied (use --upgrade to upgrade): python-consul<=0.5.0,>=0.4.0 in /usr/lib/python2.7/site-packages (from vanilla.consul)
Collecting vanilla>=0.1.14 (from vanilla.consul)
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/site-packages (from python-consul<=0.5.0,>=0.4.0->vanilla.consul)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4 in /usr/lib/python2.7/site-packages (from python-consul<=0.5.0,>=0.4.0->vanilla.consul)
Collecting greenlet (from vanilla>=0.1.14->vanilla.consul)
  Using cached greenlet-0.4.9.tar.gz
Building wheels for collected packages: greenlet
  Running setup.py bdist_wheel for greenlet
  Complete output from command /bin/python -c "import setuptools;**file**='/tmp/pip-build-em4iuq/greenlet/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" bdist_wheel -d /tmp/tmprPsOMLpip-wheel-:
  running bdist_wheel
  running build
  running build_ext
  building 'greenlet' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c greenlet.c -o build/temp.linux-x86_64-2.7/greenlet.o
  unable to execute gcc: No such file or directory
  error: command 'gcc' failed with exit status 1

---

  Failed building wheel for greenlet
Failed to build greenlet
Installing collected packages: greenlet, vanilla, vanilla.consul
  Running setup.py install for greenlet
    Complete output from command /bin/python -c "import setuptools, tokenize;**file**='/tmp/pip-build-em4iuq/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-nkvMPj-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'greenlet' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c greenlet.c -o build/temp.linux-x86_64-2.7/greenlet.o
    unable to execute gcc: No such file or directory
    error: command 'gcc' failed with exit status 1

```
----------------------------------------
```

Command "/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip-build-em4iuq/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-nkvMPj-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-em4iuq/greenlet

**Comment by mg03** [comment]
Sorry forgot to install gcc and its dependencies.

**Comment by cablehead** [comment]
It's super cool you're checking this library out. Let me know if you have
any issues!
